name: PR workflow
description: Runs main.py, runs only functions specified in 'action'
inputs:
  token:
    required: true
    description: Token of the user that creates the issue
    default: ${{ github.token }}
  action:
    required: true
    description: Desired action. i.e - add_reviewers, labels_by_user_inpurt, size_label_prs
  reviewers:
    required: false
    description: Reviewers to add to each PR.
  pypi_token:
    required: false
    description: PyPI token.

runs:
  using: docker
  image: 'Dockerfile'

branding:
  icon: arrow-down
  color: blue
