name: PR Actions
on: pull_request_target

jobs:
  initial_assignments:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Remove Merge Checks
        uses: ./
        with:
          token: ${{secrets.REPO_TOKEN}}
          action: remove_merge_checks

      - name: Check Semver Label Exists
        uses: ./
        with:
          token: ${{secrets.REPO_TOKEN}}
          action: check_semver_label_exists

      - name: Assign Size Labels
        uses: ./
        with:
          token: ${{secrets.REPO_TOKEN}}
          reviewers: myakove
          action: size_label_prs

      - name: Assign Reviewers
        uses: ./
        with:
          token: ${{secrets.REPO_TOKEN}}
          reviewers: myakove,rnetser,AdiZav
          action: add_reviewers
